# Generated by Django 6.0.1 on 2026-01-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
