# Generated by Django 6.0.1 on 2026-01-08 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_infos_lien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infos',
            name='lien',
        ),
    ]
