# Generated by Django 6.0.1 on 2026-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_infos_lien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('lien', models.URLField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=1000, null=True)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='infos',
        ),
    ]
