# Generated by Django 6.0.1 on 2026-01-09 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_info_delete_infos'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
