# Generated by Django 6.0.1 on 2026-01-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_info_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='id',
        ),
        migrations.AlterField(
            model_name='info',
            name='titre',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
