# Generated by Django 6.0.1 on 2026-01-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_remove_info_id_alter_info_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='titre',
            field=models.CharField(max_length=100),
        ),

        migrations.AddField(
            model_name='info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
