# Generated by Django 6.0.1 on 2026-01-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_info_id_alter_info_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='lien',
            field=models.URLField(),
        ),
    ]
